name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2 # 官方提供的 pnpm 安装动作
        with:
          version: 10 # 指定 pnpm 版本（如 10.x）

      - name: Install dependencies
        run: pnpm install

      - name: Create version bump and changelog
        run: pnpm changeset version

      - name: Commit version changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: release"
        continue-on-error: true # 如果没有变更文件，允许跳过提交

      - name: Push changes
        run: git push

      - name: Build all packages
        run: pnpm build

      - name: Publish packages to npm
        run: pnpm changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
